# Generated by Django 5.2.5 on 2025-08-11 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_productgallery'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='favorite_products',
            field=models.ManyToManyField(to='market.product'),
        ),
    ]
