# Generated by Django 5.2.5 on 2025-08-12 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_remove_product_category'),
        ('users', '0002_customuser_favorite_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cart_products',
            field=models.ManyToManyField(blank=True, related_name='cart_users', to='market.product'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='favorite_products',
            field=models.ManyToManyField(blank=True, related_name='favorite_users', to='market.product'),
        ),
    ]
