# Generated by Django 5.2.5 on 2025-08-30 05:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_cartitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='cart_products',
        ),
        migrations.AlterField(
            model_name='customuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
