# Generated by Django 5.2.5 on 2025-08-12 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0002_productgallery'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='category',
        ),
    ]
