# Generated by Django 5.2.5 on 2025-08-13 07:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0003_remove_product_category'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ProductCategory',
        ),
    ]
