# Generated by Django 5.2.5 on 2025-08-15 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0004_delete_productcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='quantity',
            field=models.PositiveIntegerField(default=0, verbose_name='Количество'),
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=models.TextField(verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Название'),
        ),
        migrations.AlterField(
            model_name='product',
            name='preview_image',
            field=models.ImageField(upload_to='products_preview_images/', verbose_name='Изображение товара'),
        ),
    ]
