# Generated by Django 5.2.5 on 2026-01-27 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('market', '0007_productrating'),
    ]

    operations = [
        migrations.AddField(
            model_name='productrating',
            name='comment',
            field=models.TextField(blank=True, null=True),
        ),
    ]
